const strings = {
	en: {
		title: 'Profile',
		follows: 'Following',
		followers: 'Followers',
		createdQuizzes: 'Created Quizzes',
		games: 'Games played',
		stats: 'Statistics',
		achv: 'Achivements',
		points: 'Total Points',
		changeName: 'Change name',
		validate: 'Validate',
		validate2: 'Validated User',
		follow: 'Follow',
		unfollow: 'Unfollow',
		//Achivements==>
		achiv1Title: 'Quiz Genius',
		achiv1Text: 'First quiz created',
		achiv2Title: 'PentaQuizzer',
		achiv2Text: '5 quizzes created',
		achiv3Title: 'King of the Quiz',
		achiv3Text: '10 quizzes created',
		achiv4Title: 'QuizMeApp Lover',
		achiv4Text: '25 quizzes created',
		achiv5Title: 'First Game!',
		achiv5Text: "You've played your first quiz",
		achiv6Title: 'PentaGame',
		achiv6Text: 'You have completed 5 quizzes',
		achiv7Title: 'Hooked',
		achiv7Text: 'You have completed 20 quizzes',
		achiv8Title: 'Quizminator!!!',
		achiv8Text: 'You have completed 50 quizzes',
		achiv9Title: 'Influencer',
		achiv9Text: 'User validated',
		achiv10Title: 'QuizzMeApp Friend',
		achiv10Text: 'You have acquired the membership',
		achiv11Title: 'First Like',
		achiv11Text: 'You have given your first like',
		achiv12Title: 'The liker',
		achiv12Text: 'You have given 5 likes',
		achiv13Title: 'Community lover',
		achiv13Text: 'You have given 20 likes',
		achiv14Title: 'The Lord of the Likes',
		achiv14Text: 'You have given 50 likes',
	},

	es: {
		title: 'Perfil',
		follows: 'Siguiendo a',
		followers: 'Seguidores',
		createdQuizzes: 'Quizzes Creadas',
		games: 'Partidas jugadas',
		stats: 'Estadísticas',
		achv: 'Logros',
		points: 'Puntos Totales',
		changeName: 'Cambiar nombre',
		validate: 'Validar',
		validate2: 'Usuario Validado',
		follow: 'Seguir',
		unfollow: 'Dejar de Seguir',
		//Achivements==>
		achiv1Title: 'Genio del Quiz',
		achiv1Text: 'Primer quiz creada',
		achiv2Title: 'PentaQuizzer',
		achiv2Text: '5 quizzes creadas',
		achiv3Title: 'Rey del Quiz',
		achiv3Text: '10 quizzes creadas',
		achiv4Title: 'QuizMeApp Lover',
		achiv4Text: '25 quizzes creadas',
		achiv5Title: 'Primer Juego!',
		achiv5Text: 'Haz jugado tu primer quiz',
		achiv6Title: 'PentaGame',
		achiv6Text: 'Haz completado 5 quizzes',
		achiv7Title: 'Enganchado',
		achiv7Text: 'Haz completado 20 quizzes',
		achiv8Title: 'Quizminator!!!',
		achiv8Text: 'Haz completado 50 quizzes',
		achiv9Title: 'Influencer',
		achiv9Text: 'Usuario Validado',
		achiv10Title: 'Amigo de QuizzMeApp',
		achiv10Text: 'Haz adquirido la membresia',
		achiv11Title: 'Primer Like',
		achiv11Text: 'Haz dado tu primer like',
		achiv12Title: 'The liker',
		achiv12Text: 'Haz dado 5 likes',
		achiv13Title: 'Fan de la comunidad',
		achiv13Text: 'Haz dado 20 likes',
		achiv14Title: 'El Señor de los Likes',
		achiv14Text: 'Haz dado 50 likes',
	},
};

export default strings;
