const strings = {
	en: {
		profile: 'View profile',
		acc: 'Account: ',
		free: 'Free',
		premium: 'Premium',
		premiumBtn: 'Go Premium',
		subs: 'Subscriptions',
		myQuiz: 'My Quizzes',
		email: 'Change my email:',
		user: 'Change username',
		pass: 'Change password',
		notif: 'Notification settings',
		vibration: 'Vibration',
		sound: 'Sound',
		dark: 'Dark mode',
		dark1: 'Activated',
		dark2: 'Disabled',
		lang: 'Language: ',
		help: 'Help center',
		rate: 'Rate us!',
		info: 'Information',
		version: 'Version',
		logout: 'Log Out',
		sure: 'Are you sure?',
		adminPanel: 'Admin Panel',
	},

	es: {
		profile: 'Ver perfil',
		acc: 'Cuenta: ',
		free: 'Gratis',
		premium: 'Premium',
		premiumBtn: 'Hacete Premium',
		subs: 'Suscripciones',
		myQuiz: 'Mis Quizzes',
		email: 'Cambiar mi correo:',
		user: 'Cambiar nombre de usuario',
		pass: 'Cambiar contraseña',
		notif: 'Configuración de notificaciones',
		vibration: 'Vibración',
		sound: 'Sonido',
		dark: 'Modo oscuro',
		dark1: 'Activado',
		dark2: 'Desactivado',
		lang: 'Idioma: ',
		help: 'Centro de ayuda',
		rate: '¡Valóranos!',
		info: 'Información',
		version: 'Versión',
		logout: 'Cerrar sesión',
		sure: '¿Estás seguro?',
		adminPanel: 'Panel de Admin',
	},
};

export default strings;
