const strings = {
	en: {
		nav: 'Create Quiz',
		nav2: 'Quiz Detail',
		title: "Let's start creating your own quiz",
		title2: 'What questions do you want to ask?',
		title2_1: 'Minimum 4 questions',
		titlePlace: 'Title',
		descPlace: 'Description',
		img: 'Image (Optional)',
		img1: 'Change the selected image',
		img2: 'Choose an image',
		permit: 'We need permission to you gallery',
		cat: 'Category',
		lang: 'Language',
		time: 'Time of each question (in seconds)',
		next: 'Next',
		finish: 'Finish',
		question: 'Question',
		option: 'Option ',
		correct: 'Choose the correct option',
		seconds: 'seconds per question',
		ques: 'Questions',
		fin: 'Finish',
		req: 'Required',
		req2: 'Choose a category for your quiz.',
		req3: 'Choose a language for your quiz.',
		youSure: 'Are you sure?',
		noEdit: "You won't be able to edit the quiz",
		cancel: 'Cancel',
		finishEdit: 'Finish edit',
		typeClassic: 'Classic',
		typeBoolean: 'True/False',
		true: 'True',
		false: 'False',
	},

	es: {
		nav: 'Crear Quiz',
		nav2: 'Detalles del Quiz',
		title: 'Empecemos a crear tu propia quiz',
		title2: '¿Que preguntas quieres hacer?',
		title2_1: 'Mínimo 4 preguntas',
		titlePlace: 'Título',
		descPlace: 'Descripción',
		img: 'Imagen (Opcional)',
		img1: 'Cambia la imagen seleccionada',
		img2: 'Elige una imagen',
		permit:
			'Necesitamos permiso a tu galería para que puedas subir una imagen',
		cat: 'Categoría',
		lang: 'Lenguaje',
		time: 'Tiempo de cada pregunta (en segundos)',
		next: 'Siguiente',
		finish: 'Finalizar',
		question: 'Pregunta',
		option: 'Opción ',
		correct: 'Elige la opción correcta',
		seconds: 'segundos por pregunta',
		ques: 'Preguntas',
		fin: 'Finalizar',
		req: 'Requerido',
		req2: 'Elige una categoría para tu quiz.',
		req3: 'Elige un lenguaje para tu quiz.',
		youSure: 'Are you sure?',
		noEdit: 'Una vez creado el quiz no podrás editarlo',
		cancel: 'Cancelar',
		finishEdit: 'Finalizar edición',
		typeClassic: 'Clasica',
		typeBoolean: 'Verdadero/Falso',
		true: 'Verdadero',
		false: 'Falso',
	},
};

export default strings;
