const strings = {
	en: {
		nav: 'Create Quiz',
		nav2: 'Quiz Detail',
		title: "Let's start creating your own quiz",
		title2: 'What questions do you want to ask?',
		title2_1: 'Minimum 4 questions',
		titlePlace: 'Title',
		descPlace: 'Description',
		img: 'Image (Optional)',
		img1: 'Change the selected image',
		img2: 'Choose an image',
		cat: 'Category',
		time: 'Time of each question (in seconds)',
		next: 'Next',
		finish: 'Finish',
		question: 'Question',
		option1: 'Option 1',
		option2: 'Option 2',
		option3: 'Option 3',
		option4: 'Option 4',
		correct: 'Choose the correct option',
		seconds: 'seconds per question',
		ques: 'Questions',
		fin: 'Finish',
		req: 'Required',
		req2: 'Choose a category for your quiz.',
	},

	es: {
		nav: 'Crear Quiz',
		nav2: 'Detalles del Quiz',
		title: 'Empecemos a crear tu propia quiz',
		title2: '¿Que preguntas quieres hacer?',
		title2_1: 'Mínimo 4 preguntas',
		titlePlace: 'Título',
		descPlace: 'Descripción',
		img: 'Imagen (Opcional)',
		img1: 'Cambia la imagen seleccionada',
		img2: 'Elige una imagen',
		cat: 'Categoría',
		time: 'Tiempo de cada pregunta (en segundos)',
		next: 'Siguiente',
		finish: 'Finalizar',
		question: 'Pregunta',
		option1: 'Opción 1',
		option2: 'Opción 2',
		option3: 'Opción 3',
		option4: 'Opción 4',
		correct: 'Elige la opción correcta',
		seconds: 'segundos por pregunta',
		ques: 'Preguntas',
		fin: 'Finalizar',
		req: 'Requerido',
		req2: 'Elegir una categoría para tu quiz.',
	},
};

export default strings;
